[package]
name = "smart_contract_upgrade"
version = "0.1.0"
edition = "2024"
license = "MPL-2.0"
authors = ["Concordium <developers@concordium.com>"]
description = "An example of how to upgrade a smart contract. The state is migrated during the upgrade."

[dependencies]
concordium-std = {path = "../../../concordium-std"}

[dev-dependencies]
concordium-smart-contract-testing = { path = "../../../contract-testing" }
concordium-std-derive = { path = "../../../concordium-std-derive" }

[lib]
crate-type=["cdylib", "rlib"]

[profile.release]
opt-level = "s"
codegen-units = 1
