[package]
name = "credential_registry"
version = "0.1.0"
edition = "2024"
license = "MPL-2.0"
authors = [ "Concordium <developers@concordium.com>" ]
description = "Example-credential-registry"

[dependencies]
concordium-std = {path = "../../concordium-std"}
concordium-cis2 = {path = "../../concordium-cis2"}

[dev-dependencies]
concordium-smart-contract-testing = {path = "../../contract-testing"}
concordium-std-derive = {path = "../../concordium-std-derive"}

[lib]
crate-type=["cdylib", "rlib"]


