[package]
name = "cis2_nft"
version = "0.1.0"
authors = [ "Concordium <developers@concordium.com>" ]
edition = "2024"
license = "MPL-2.0"
description = "cis2-nft-project"

[dependencies]
concordium-std = {path = "../../concordium-std"}
concordium-cis2 = {path = "../../concordium-cis2"}

[dev-dependencies]
concordium-smart-contract-testing = {path = "../../contract-testing"}
concordium-std-derive = {path = "../../concordium-std-derive"}

[lib]
crate-type=["cdylib", "rlib"]
