[package]
name = "piggy-bank-part1"
version = "0.1.1"
authors = ["Concordium <developers@concordium.com>"]
edition = "2024"
license = "MPL-2.0"
description = "Piggy bank smart contract part 1."
homepage = "https://github.com/concordium/concordium-rust-smart-contracts"
repository = "https://github.com/concordium/concordium-rust-smart-contracts"
readme = "../README.md"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies.concordium-std]
path = "../../../concordium-std"
