[package]
name = "concordium-std"
version = "10.1.0"
authors = ["Concordium <developers@concordium.com>"]
edition = "2024"
rust-version = "1.85"
license = "MPL-2.0"
description = "A standard library for writing smart contracts for the Concordium blockchain in Rust."
homepage = "https://github.com/Concordium/concordium-rust-smart-contracts/"
repository = "https://github.com/Concordium/concordium-rust-smart-contracts/"
readme = "./README.md"

[dependencies]
quickcheck = {version = "1", optional = true }
getrandom = { version = "0.2", features = ["custom"], optional = true }

[dependencies.concordium-contracts-common]
path = "../concordium-rust-sdk/concordium-base/smart-contracts/contracts-common/concordium-contracts-common"
version = "9.0"
default-features = false
features = ["smart-contract"]

[features]
default = ["bump_alloc"]
# Enabling the wasm-test feature changes the #[concoridum_test] macro to output test functions callable from WASM interpreter
wasm-test = ["concordium-contracts-common/wasm-test"]
# Own internal wasm-tests leak out to the smart contracts using this library,
# so a separate feature 'internal-wasm-test' is introduced for these.
internal-wasm-test = ["wasm-test"]
#internal-wasm-test = ["wasm-test", "concordium-quickcheck"] # todo ar
# Make smart contract macros generate function in the smart contract that allows inspecting the schema of the contract functions.
build-schema = ["concordium-contracts-common/build-schema"]
concordium-quickcheck = ["getrandom", "quickcheck", "concordium-contracts-common/concordium-quickcheck"] # // todo ar "std"
# Enabling debug feature changes the #[concoridum_dbg] macro to log messages via the WASM interpreter
debug = []
# Custom allocator. See module documentation for bump_alloc in this crate
bump_alloc = []

[lib]
# cdylib is needed below to compile into a wasm module with internal unit tests.
crate-type = ["cdylib", "rlib"]

[profile.release]
# Tell `rustc` to optimize for small code size.
opt-level = "s"

[dev-dependencies]
trybuild = "1.0"

[package.metadata.docs.rs]
# This sets the default target to `wasm32v1-none` and only builds that
# target on docs.rs. This is useful because the some parts of documentation only
# exist on that platform.
targets = ["wasm32v1-none"]
