[package]
name = "transfer-policy-check"
version = "0.1.0"
authors = ["Concordium <developers@concordium.com>"]
edition = "2021"
license = "MPL-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
concordium-std = {path = "../../concordium-std", default-features = false}

[dev-dependencies]
concordium-smart-contract-testing = { path = "../../contract-testing" }
concordium-std-derive = { path = "../../concordium-std-derive" }

[features]
default = ["std", "bump_alloc"]
std = ["concordium-std/std"]
bump_alloc = ["concordium-std/bump_alloc"]

[lib]
crate-type=["cdylib", "rlib"]

[profile.release]
opt-level = 3
panic = "abort"
