[package]
name = "proxy"
version = "0.1.0"
authors = ["Concordium <developers@concordium.com>"]
edition = "2024"
license = "MPL-2.0"

[dependencies]
concordium-std = {path = "../../concordium-std"}
concordium-std-derive = { path = "../../concordium-std-derive" }

[dev-dependencies]
concordium-smart-contract-testing = { path = "../../contract-testing" }

[lib]
crate-type = ["cdylib", "rlib"]
