[package]
name = "signature-verifier"
version = "0.1.0"
authors = ["Concordium <developers@concordium.com>"]
edition = "2018"
license = "MPL-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
concordium-std = {path = "../../concordium-std"}

[features]
default = ["std"]
std = ["concordium-std/std"]
crypto-utils = ["concordium-std/crypto-utils"]

[lib]
crate-type=["cdylib", "rlib"]
