[package]
name = "signature-verifier"
version = "0.1.0"
authors = ["Concordium <developers@concordium.com>"]
edition = "2024"
license = "MPL-2.0"

[dependencies]
concordium-std = {path = "../../concordium-std"}

[dev-dependencies]
concordium-smart-contract-testing = { path = "../../contract-testing" }
concordium-std-derive = { path = "../../concordium-std-derive" }
ed25519-dalek = { version = "2.0", features = ["rand_core"]  }
rand = "0.8.5"

[lib]
crate-type=["cdylib", "rlib"]
