# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[package]
name = "account_signature_checks"
version = "0.1.0"
edition = "2024"
license = "MPL-2.0"
authors = [ "Concordium <developers@concordium.com>" ]
description = "An example of how to check account signatures"

[dependencies]
concordium-std = {path = "../../concordium-std"}

[lib]
crate-type=["cdylib", "rlib"]

[profile.release]
opt-level = "s"
codegen-units = 1
