[package]
name = "cts1-nft"
version = "0.1.0"
authors = ["Concordium <developers@concordium.com>"]
edition = "2018"
license = "MPL-2.0"

[features]
default = ["std"]
std = ["concordium-std/std", "concordium-cts/std"]

[dependencies]
concordium-std = {path = "../../concordium-std", default-features = false}
concordium-cts = {path = "../../concordium-cts", default-features = false}

[lib]
crate-type=["cdylib", "rlib"]

[profile.release]
opt-level = "s"
