# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[package]
name = "smart_contract_upgrade"
version = "0.2.0"
edition = "2024"
license = "MPL-2.0"
authors = ["Concordium <developers@concordium.com>"]
description = "An example of how to upgrade a smart contract. The state is migrated during the upgrade."

[dependencies]
concordium-std = {path = "../../../concordium-std"}

[lib]
crate-type=["cdylib", "rlib"]

[profile.release]
opt-level = "s"
codegen-units = 1
