[package]
name = "smart-contract-oracle-integration"
version = "0.1.0"
authors = ["Concordium <developers@concordium.com>"]
edition = "2021"
license = "MPL-2.0"
description = "An example of how to read price data from the umbrella oracle."

[dependencies]
concordium-std = {path = "../../concordium-std", default-features = false}

[dev-dependencies]
concordium-smart-contract-testing = { path = "../../contract-testing" }
ed25519-dalek = { version = "2.0", features = ["rand_core"]  }

[features]
default = ["std", "wee_alloc"]
std = ["concordium-std/std"]
wee_alloc = ["concordium-std/wee_alloc"]

[lib]
crate-type=["cdylib", "rlib"]
