on:
  push:
    branches:
      - main
  pull_request:
    branches:

  workflow_dispatch: # allows manual trigger

name: Clippy & fmt

env:
  CARGO_CONCORDIUM_VERSION: "4.2.0"

jobs:

  rustfmt:
    name: Format
    if: ${{ !github.event.pull_request.draft }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Format
        run: |
          rustup component add rustfmt
          cargo fmt -- --color=always --check    

  rustdoc:
    name: Lint docs
    if: ${{ !github.event.pull_request.draft }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Docs
        run: |
          rustup component add rust-docs
          RUSTDOCFLAGS="-D warnings" cargo doc --no-deps --all-features

  clippy:
    name: Clippy
    if: ${{ !github.event.pull_request.draft }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Clippy
        run: |
          rustup component add clippy
          cargo clippy --color=always --all-targets --all-features -- -D warnings

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Test
        run: cargo test --all-features -- --skip io_tests # Skip the I/O tests in the testing library.

  # Run unit-tests for concordium-std compiled to wasm using cargo concordium test.
  std-internal-wasm-test:
    name: concordium-std internal wasm tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout sources
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Run internal wasm unit test
        working-directory: concordium-std
        run: |
          # curl -L https://github.com/Concordium/concordium-smart-contract-tools/releases/download/releases/cargo-concordium/${CARGO_CONCORDIUM_VERSION}/cargo-concordium-linux-amd64 -o /tmp/cargo-concordium
          # chmod +x /tmp/cargo-concordium
          # sudo mv /tmp/cargo-concordium /usr/bin/cargo-concordium
          # todo change to use release as part of https://linear.app/concordium/issue/COR-2479/release-for-wasm32v1
          cargo install --git https://github.com/Concordium/concordium-smart-contract-tools.git --branch ar/cor-2468-update-cargo-concordium-to-use-wasm32v1-target --locked
          cargo concordium test --only-unit-tests -- --features internal-wasm-test

  std_clippy_wasm32v1:
    name: Clippy on concordium-std for wasm32v1 target
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Run cargo check
        working-directory: concordium-std
        run: |
          rustup component add clippy
          rustup target add wasm32v1-none          
          cargo clippy --target wasm32v1-none -- -D warnings

  std_check:
    name: Check on concordium-std for x64 and wasm32 and different features
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Run cargo check
        working-directory: concordium-std
        run: |
          # Try different feature combinations on default (x86 linux) target
          cargo check

          # Try different feature combinations on wasm32v1 target
          rustup target add wasm32v1-none
          cargo check --target wasm32v1-none 
          cargo check --target wasm32v1-none --features wasm-test
          cargo check --target wasm32v1-none --features build-schema
          cargo check --target wasm32v1-none --features bump_alloc
          cargo check --target wasm32v1-none --features debug

  cis2_check:
    name: Check on concordium-cis2 for x64 and wasm32 and different features
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Run cargo check
        working-directory: concordium-cis2
        run: |
          # Try different feature combinations on default (x86 linux) target
          cargo check
          cargo check --features serde
          cargo check --features u256_amount
          cargo check --all-features

          # Try different feature combinations on wasm32v1 target
          rustup target add wasm32v1-none
          cargo check --target wasm32v1-none 
          cargo check --target wasm32v1-none --features u256_amount


  examples-rustfmt:
    name: Examples format
    if: ${{ !github.event.pull_request.draft }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Format
        working-directory: examples
        run: |
          rustup component add rustfmt
          cargo fmt -- --color=always --check  

  examples-clippy:
    name: Examples clippy
    if: ${{ !github.event.pull_request.draft }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Clippy
        working-directory: examples
        run: |
          rustup component add clippy
          cargo clippy --color=always --all-targets --all-features -- -D warnings

  examples_check:
    name: Check on examples using wasm32v1 target
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Run cargo check
        working-directory: examples
        run: |
          rustup target add wasm32v1-none
          cargo check --target wasm32v1-none 

#  examples_test:
#    name: Test examples
#    runs-on: ubuntu-latest
#    needs: [rustfmt, clippy-schema]
#    strategy:
#      matrix:
#        crates:
#          - examples/voting
#          - examples/eSealing
#          - examples/auction
#          - examples/cis2-multi
#          - examples/cis2-dynamic-nft
#          - examples/cis2-multi-royalties
#          - examples/cis2-nft
#          - examples/cis3-nft-sponsored-txs
#          - examples/cis2-wccd
#          - examples/cis5-smart-contract-wallet
#          - examples/credential-registry
#          - examples/factory
#          - examples/fib
#          - examples/icecream
#          - examples/memo
#          - examples/nametoken
#          - examples/piggy-bank/part1
#          - examples/piggy-bank/part2
#          - examples/proxy
#          - examples/recorder
#          - examples/signature-verifier
#          - examples/transfer-policy-check
#          - examples/two-step-transfer
#          - examples/smart-contract-upgrade/contract-version1
#          - examples/smart-contract-upgrade/contract-version2
#          - examples/offchain-transfers
#          - examples/account-signature-checks
#          - examples/sponsored-tx-enabled-auction
#          - examples/bump-alloc-tests
#
#    steps:
#      - name: Checkout sources
#        uses: actions/checkout@v2
#        with:
#          submodules: recursive
#
#      - name: Install toolchain
#        uses: actions-rust-lang/setup-rust-toolchain@v1
#        with:
#          toolchain: ${{ env.RUST_VERSION_TESTING_LIBRARY }}
#          target: wasm32-unknown-unknown
#
#      - name: Download and install Cargo Concordium
#        run: |
#          # curl -L https://github.com/Concordium/concordium-smart-contract-tools/releases/download/releases/cargo-concordium/${CARGO_CONCORDIUM_VERSION}/cargo-concordium-linux-amd64 -o /tmp/cargo-concordium
#          # chmod +x /tmp/cargo-concordium
#          # sudo mv /tmp/cargo-concordium /usr/bin/cargo-concordium
#          # todo change to use release as part of https://linear.app/concordium/issue/COR-2479/release-for-wasm32v1
#          cargo install --git https://github.com/Concordium/concordium-smart-contract-tools.git --branch ar/cor-2468-update-cargo-concordium-to-use-wasm32v1-target --locked
#        # The 'smart-contract-upgrade' example has a v1 and v2 contract and the tests in v1 needs the wasm module from v2 for upgrading.
#      - name: Build contract-upgrade version 2 module if needed
#        if: ${{ matrix.crates == 'examples/smart-contract-upgrade/contract-version1' }}
#        run: cargo concordium build --out "examples/smart-contract-upgrade/contract-version2/concordium-out/module.wasm.v1" -- --manifest-path "examples/smart-contract-upgrade/contract-version2/Cargo.toml"
#
#        # The 'sponsored-tx-enabled-auction' and 'cis5-smart-contract-wallet' examples need the wasm module `cis2-multi` for its tests.
#      - name: Build cis2-multi module if needed
#        if: ${{ matrix.crates == 'examples/sponsored-tx-enabled-auction' || matrix.crates == 'examples/cis5-smart-contract-wallet'}}
#        run: cargo concordium build --out "examples/cis2-multi/concordium-out/module.wasm.v1" -- --manifest-path "examples/cis2-multi/Cargo.toml"
#
#      - name: Run cargo concordium test
#        run: cargo concordium test --out "${{ matrix.crates }}/concordium-out/module.wasm.v1" -- --manifest-path "${{ matrix.crates }}/Cargo.toml"
