name: "Testing library: Format, lint, build, and test"

# This job runs:
# - rustfmt
# - rustdoc
# - clippy linting
# - tests
# for the smart contract testing library.

on:
  push:
    branches: main

  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review
    paths:
      - 'contract-testing/**/*.rs'
      - 'contract-testing/**/*.toml'
      - 'rustfmt.toml'
      - 'concordium-rust-sdk'
      - 'concordium-std-derive'

  workflow_dispatch: # allows manual trigger

jobs:
  "lint_fmt":
    name: contract-testing lint:fmt
    # Don't run on draft pull requests
    if: ${{ !github.event.pull_request.draft }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Format
        working-directory: contract-testing
        run: |
          rustup component add rustfmt
          cargo fmt -- --color=always --check

  "lint_doc":
    name: contract-testing lint:doc
    # Don't run on draft pull requests
    if: ${{ !github.event.pull_request.draft }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Docs
        working-directory: contract-testing
        run: |
          rustup component add rust-docs
          RUSTDOCFLAGS="-D warnings" cargo doc --no-deps --all-features

  "lint_clippy":
    name: contract-testing lint:clippy
    # Don't run on draft pull requests
    if: ${{ !github.event.pull_request.draft }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Clippy
        working-directory: contract-testing
        run: |
          rustup component add clippy
          cargo clippy --color=always --all-targets --all-features -- -D warnings

  "cargo_test":
    name: contract-testing cargo:test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Test
        working-directory: contract-testing
        run: cargo test -- --skip io_tests # Skip the I/O tests in the testing library.
